---
- name: Configure Apache Web Server on all VMs
  hosts: webservers
  become: yes
  gather_facts: yes

  vars:
    server_name: "{{ inventory_hostname }}"
    document_root: /var/www/html

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - packages

    - name: Install Apache2 web server
      ansible.builtin.apt:
        name:
          - apache2
          - curl
        state: present
      tags:
        - packages

    - name: Ensure Apache2 is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
      tags:
        - service

    - name: Create custom index.html
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>{{ inventory_hostname }} - Terraform + Ansible</title>
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }
                  body {
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      padding: 20px;
                  }
                  .container {
                      background: white;
                      padding: 50px;
                      border-radius: 20px;
                      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                      max-width: 700px;
                      width: 100%;
                      animation: slideIn 0.5s ease-out;
                  }
                  @keyframes slideIn {
                      from {
                          opacity: 0;
                          transform: translateY(-30px);
                      }
                      to {
                          opacity: 1;
                          transform: translateY(0);
                      }
                  }
                  h1 {
                      color: #667eea;
                      margin-bottom: 30px;
                      font-size: 3em;
                      text-align: center;
                  }
                  .badge {
                      display: inline-block;
                      background: #667eea;
                      color: white;
                      padding: 5px 15px;
                      border-radius: 20px;
                      font-size: 0.9em;
                      margin-bottom: 20px;
                  }
                  .info-grid {
                      display: grid;
                      grid-template-columns: 1fr 1fr;
                      gap: 20px;
                      margin: 30px 0;
                  }
                  .info-card {
                      background: #f8f9fa;
                      padding: 20px;
                      border-radius: 10px;
                      border-left: 4px solid #667eea;
                  }
                  .info-label {
                      font-weight: bold;
                      color: #667eea;
                      font-size: 0.9em;
                      margin-bottom: 5px;
                  }
                  .info-value {
                      color: #333;
                      font-size: 1.1em;
                  }
                  .success-box {
                      background: linear-gradient(135deg, #d4edda 0%, #c3e6cb 100%);
                      color: #155724;
                      padding: 20px;
                      border-radius: 10px;
                      margin-top: 30px;
                      border-left: 4px solid #28a745;
                      text-align: center;
                      font-size: 1.1em;
                  }
                  .tech-stack {
                      display: flex;
                      justify-content: center;
                      gap: 15px;
                      margin-top: 20px;
                      flex-wrap: wrap;
                  }
                  .tech-badge {
                      background: #764ba2;
                      color: white;
                      padding: 8px 16px;
                      border-radius: 5px;
                      font-size: 0.9em;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <span class="badge">🚀 Live Server</span>
                  <h1>{{ inventory_hostname }}</h1>
                  
                  <div class="info-grid">
                      <div class="info-card">
                          <div class="info-label">🖥️ Hostname</div>
                          <div class="info-value">{{ inventory_hostname }}</div>
                      </div>
                      <div class="info-card">
                          <div class="info-label">🌐 IP Address</div>
                          <div class="info-value">{{ ansible_host }}</div>
                      </div>
                      <div class="info-card">
                          <div class="info-label">💿 Operating System</div>
                          <div class="info-value">{{ ansible_distribution }}</div>
                      </div>
                      <div class="info-card">
                          <div class="info-label">⚙️ Architecture</div>
                          <div class="info-value">{{ ansible_architecture }}</div>
                      </div>
                  </div>
                  
                  <div class="success-box">
                      ✅ <strong>Successfully Deployed!</strong><br>
                      Infrastructure provisioned with Terraform<br>
                      Configuration managed with Ansible
                  </div>
                  
                  <div class="tech-stack">
                      <span class="tech-badge">Terraform</span>
                      <span class="tech-badge">Ansible</span>
                      <span class="tech-badge">Ubuntu</span>
                      <span class="tech-badge">Apache</span>
                      <span class="tech-badge">VirtualBox</span>
                  </div>
              </div>
          </body>
          </html>
        dest: "{{ document_root }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'
      tags:
        - content

    - name: Configure Apache to listen on correct port
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 80'
        state: present
      notify: restart apache
      tags:
        - config

    - name: Allow HTTP through UFW firewall
      ansible.builtin.ufw:
        rule: allow
        port: '80'
        proto: tcp
      ignore_errors: yes
      tags:
        - firewall

  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted